# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: docker
    directory: /
    labels:
      - dependencies
      - docker
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependencies
      - go
    schedule:
      interval: weekly
      day: sunday
    ignore:
      - dependency-name: "k8s.io/api"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "k8s.io/apimachinery"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "k8s.io/client-go"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "k8s.io/cloud-provider"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "k8s.io/component-base"
        update-types: ["version-update:semver-minor"]
