version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goheader
    - gomoddirectives
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - tagliatelle
    - testpackage
    - varnamelen
    - wsl
    # TODO: Following Lint issues need to be fixed:
    - embeddedstructfieldcheck
    - funcorder
    - wsl_v5
    - noinlineerr
  settings:
    nolintlint:
      allow-unused: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - forbidigo
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - maintidx
        path: (.+)_test.go$
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/apache/cloudstack-kubernetes-provider)
    gofumpt:
      module-path: github.com/apache/cloudstack-kubernetes-provider
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
