linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/apache/cloudstack-kubernetes-provider)
  gofumpt:
    module-path: "github.com/apache/cloudstack-kubernetes-provider"
  nolintlint:
    # https://github.com/golangci/golangci-lint/issues/3228
    allow-unused: true

linters:
  disable:
    - goheader
    - depguard
    - wrapcheck
    - mnd
    - varnamelen
    - testpackage
    - tagliatelle
    - paralleltest
    - ireturn
    - err113
    - gochecknoglobals
    - wsl
    - exhaustive
    - nosprintfhostport
    - nonamedreturns
    - interfacebloat
    - exhaustruct
    - lll
    - gosec
    - gomoddirectives
    - godox
    - gochecknoinits
    - funlen
    - dupl
    - cyclop
    - inamedparam
    # deprecated linters
    - tenv
  enable-all: true

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
  exclude-rules:
    - path: (.+)_test.go$
      linters:
        - gocognit
        - goconst
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - forbidigo
        - maintidx

run:
  timeout: 10m
  allow-parallel-runners: true

