[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "k8s.io/cloud-provider"
  version = "kubernetes-1.13.0-beta.1"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.0-beta.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.13.0-beta.1"

[[constraint]]
  name = "github.com/xanzy/go-cloudstack"
  version = "v2.4.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.0-beta.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.0-beta.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.0-beta.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.0-beta.1"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"
