---
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/cloudstack-load-balancer-proxy-protocol: enabled
spec:
  type: LoadBalancer
  ports:
  - name: http-proxy
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https-proxy
    port: 443
    protocol: TCP
    targetPort: 443
---
kind: DaemonSet
# ...
spec:
  template:
    spec:
      hostNetwork: true
      containers:
      - name: my-ingress-controller
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
