---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: cloud-controller-manager
  name: cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cloud-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: cloud-controller-manager
    spec:
      priorityClassName: system-node-critical
      containers:
      - name: cloud-controller-manager
        image: cloudstack-kubernetes-provider
        imagePullPolicy: IfNotPresent
        args:
        - --leader-elect=true
        - --cloud-provider=cloudstack
        - --cloud-config=/config/cloud-config
        resources:
          limits:
            cpu: 50m
            memory: 120Mi
          requests:
            cpu: 10m
            memory: 60Mi
        volumeMounts:
        - name: config-volume
          mountPath: /config
      restartPolicy: Always
      serviceAccountName: cloud-controller-manager
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        secret:
          secretName: cloudstack-secret
