{{- if and (.Values.secret.create) (.Values.secret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "cloud-config" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  cloud.conf: {{ include "cloudConfig" . | b64enc }}
{{- end }}