apiVersion: v2
name: cloud-controller-manager
description: CloudStack Cloud Controller Manager Helm chart
type: application
version: 1.1.1
appVersion: 1.3.0
sources:
  - https://github.com/Leaseweb/cloudstack-kubernetes-provider
keywords:
  - cloudControlerManger
  - cloudProvider
  - cloudStack
