apiVersion: v2
name: cloud-controller-manager
description: CloudStack Cloud Controller Manager Helm chart
type: application
version: 1.0.6
appVersion: 1.2.1
sources:
  - https://github.com/Leaseweb/cloudstack-kubernetes-provider
keywords:
  - cloudControlerManger
  - cloudProvider
  - cloudStack
