apiVersion: v2
name: cloud-controller-manager
description: A Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: 1.0.0
sources:
  - https://github.com/Leaseweb/cloudstack-kubernetes-provider
keywords:
  - cloudControlerManger
  - cloudProvider
  - cloudStack