apiVersion: v2
name: cloud-controller-manager
description: CloudStack Cloud Controller Manager Helm chart
type: application
version: 1.5.1
appVersion: 1.7.1
sources:
  - https://github.com/leaseweb/cloudstack-kubernetes-provider
keywords:
  - cloudControlerManger
  - cloudProvider
  - cloudStack
